BlogSitesiProjesi/ViewModels/Home/Overview/OverviewViewModel.cs
using System;

namespace BlogSitesiProjesi.ViewModels.Home.Overview
{
    public class OverviewViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string Author { get; set; }
        public DateTime CreatedTime { get; set; }
        public string ArticlePicture { get; set; }

        public string GetCreatedTime()
        {
            return CreatedTime.ToString("dd-MM-yyyy HH:mm");
        }
    }
}

BlogSitesiProjesi/ViewModels/Home/Profile/ArticleViewModel.cs
using System;

namespace BlogSitesiProjesi.ViewModels.Home.Profile
{
    public class ArticleViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string AuthorId { get; set; }
        public string AuthorName { get; set; }
        public DateTime CreatedTime { get; set; }
        public string ArticlePicture { get; set; }

        public string GetCreatedTime()
        {
            return CreatedTime.ToString("dd-MM-yyyy HH:mm");
        }

        public string GetContentSummary()
        {
            int limit = 500;
            string summary = string.Empty;

            if (Content.Length >= limit)
                summary = string.Format("{0}...", Content.Substring(0, limit));
            else
                summary = Content;

            return summary;
        }
    }
}

BlogSitesiProjesi/Controllers/ArticleController.cs
using BlogSitesiProjesi.Models.Data;
using BlogSitesiProjesi.ViewModels.Article.Create;
using BlogSitesiProjesi.ViewModels.Article.Edit;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using BlogSitesiProjesi.Filters;
using BlogSitesiProjesi.Managers;
using BlogSitesiProjesi.Models.Entity;

namespace BlogSitesiProjesi.Controllers
{
    [LoggedUser]
    public class ArticleController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ArticleController(AppDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            this._context = context;
            this._webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Create(string yonlen)
        {
            ViewBag.yonlen = yonlen;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreateViewModel model, string yonlen)
        {
            if (ModelState.IsValid)
            {
                Article article = new Article
                {
                    Title = model.Title,
                    Content = model.Content,
                    AuthorId = int.Parse(HttpContext.Session.GetString("userId")),
                    ArticlePicture = model.ArticlePicture.GetUniqueNameAndSavePhotoToDisk(_webHostEnvironment)
                };
                _context.Articles.Add(article);
                _context.SaveChanges();
                TempData["message"] = "Makale Oluşturuldu..!";
                if (yonlen == null) return RedirectToAction("Index", "Home");
                return Redirect(yonlen);
            }
            else return View(model);
        }

        public IActionResult Edit(int id)
        {
            Article article = _context.Articles.FirstOrDefault(x => x.Id.Equals(id) && x.AuthorId.ToString().Equals(HttpContext.Session.GetString("userId")));

            if (article is not null) return View(new EditViewModel
            {
                Id = article.Id,
                Title = article.Title,
                Content = article.Content,
                ArticlePictureName = article.ArticlePicture
            });
            else
            {
                TempData["error"] = "Data Bulunamadı";
                return RedirectToAction("Profile", "Home", new { email = HttpContext.Session.GetString("email") });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(EditViewModel model)
        {
            if (ModelState.IsValid)
            {
                Article article = _context.Articles.FirstOrDefault(x => x.Id.Equals(model.Id) && x.AuthorId.ToString().Equals(HttpContext.Session.GetString("userId")));
                if (article is null)
                {
                    ViewData["error"] = "Düzenleme Başarısız Oldu..!";
                    return View(model);
                }

                article.Title = model.Title;
                article.Content = model.Content;

                if (model.ArticlePicture != null)
                {

                    article.ArticlePicture = model.ArticlePicture.GetUniqueNameAndSavePhotoToDisk(_webHostEnvironment);

                    FileManager.RemoveImageFromDisk(model.ArticlePictureName, _webHostEnvironment);
                }

                _context.SaveChanges();

                TempData["message"] = "Makale Güncellendi..!";
                return RedirectToAction("Profile", "Home", new { email = HttpContext.Session.GetString("email") });
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {

            Article article = _context.Articles.FirstOrDefault(x => x.Id.Equals(id) && x.AuthorId.ToString().Equals(HttpContext.Session.GetString("userId")));

            if (article is not null)
            {
                _context.Articles.Remove(article);
                _context.SaveChanges();
                FileManager.RemoveImageFromDisk(article.ArticlePicture, _webHostEnvironment);
                TempData["message"] = "Silindi..!";
            }
            else TempData["error"] = "Data Bulunamadı";

            return RedirectToAction("Profile", "Home", new { email = HttpContext.Session.GetString("email") });
        }
    }
}

BlogSitesiProjesi/Controllers/HomeController.cs
using BlogSitesiProjesi.Models;
using BlogSitesiProjesi.Models.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using BlogSitesiProjesi.Filters;
using BlogSitesiProjesi.ViewModels.Home.Overview;
using BlogSitesiProjesi.ViewModels.Home.Profile;

namespace BlogSitesiProjesi.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly AppDbContext _context;

        public HomeController(ILogger<HomeController> logger, AppDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            List<ArticleViewModel> list = _context.Articles.OrderByDescending(x => x.CreatedTime)
                                           .Take(20)
                                           .Select(x => new ArticleViewModel()
                                           {
                                               Id = x.Id,
                                               AuthorId = x.Author.Id.ToString(),
                                               AuthorName = x.Author.Email,
                                               ArticlePicture = string.IsNullOrEmpty(x.ArticlePicture) ? "null.png" : x.ArticlePicture,
                                               Title = x.Title,
                                               Content = x.Content,
                                               CreatedTime = x.CreatedTime
                                           }).ToList();
            return View(list);
        }

        [HttpGet("[controller]/[action]/{email}")]
        public IActionResult Profile(string email)
        {
            List<ArticleViewModel> list = _context.Articles
                .Where(x => x.Author.Email.Equals(email))
                .OrderByDescending(x => x.CreatedTime)
                .Select(x => new ArticleViewModel()
                {
                    Id = x.Id,
                    AuthorId = x.Author.Id.ToString(),
                    AuthorName = x.Author.Email,
                    ArticlePicture = string.IsNullOrEmpty(x.ArticlePicture) ? "null.png" : x.ArticlePicture,
                    Title = x.Title,
                    Content = x.Content,
                    CreatedTime = x.CreatedTime
                }).ToList();
            return View(list);
        }

        public IActionResult Overview(int id)
        {

            var model = _context.Articles.Select(x => new OverviewViewModel()
            {
                Id = x.Id,
                Author = x.Author.Email,
                ArticlePicture = string.IsNullOrEmpty(x.ArticlePicture) ? "null.png" : x.ArticlePicture,
                Title = x.Title,
                Content = x.Content,
                CreatedTime = x.CreatedTime
            }).FirstOrDefault(x => x.Id.Equals(id));

            return View(model);
        }

        [LoggedUser]
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BlogSitesiProjesi/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Http
@model List<ArticleViewModel>
@{
    ViewData["Title"] = "Ana Sayfa";
}

<link href="~/css/article-list.css" rel="stylesheet" />

<div class="container">
    <h2 class="text-center">Son Makaleler</h2>
    @if (TempData["message"] != null)
    {
        <div class="text-success">@TempData["message"]</div>
    }
    @if (TempData["error"] != null)
    {
        <div class="text-danger">@TempData["error"]</div>
    }

    @if (!string.IsNullOrEmpty(Context.Session.GetString("userId")))
    {
        <div style="float:right">
            <a class="btn btn-outline-success" asp-controller="Article" asp-action="Create" asp-route-yonlen="/Home/Index">
                <i class="fas fa-plus">&nbsp;&nbsp;Create</i>
                </a>
        </div>
    }
    <br>
    <br>
    @if (Model is null || Model.Count == 0)
    {
        <h2 class="text-center article-panel brick">Makale yok </h2>
    }
    else
    {
        foreach (ArticleViewModel article in Model)
        {
            <div class="row mb-2 p-1 article-panel">
                <div class="col col-9">
                    <div class="row">
                        <div class="col col-4">
                              <a asp-controller="Home" asp-action="Profile" asp-route-username="@article.AuthorName" class="black action">
                            <div class="row"><b>Author: </b> &nbsp; @article.AuthorName</div>
                            </a>
                            <div class="row">
                                <img src="~/images/@article.ArticlePicture" alt="Alternate Text" style="object-fit:contain; max-width:200px; max-height:150px;">
                            </div>
                        </div>
                        <div class="col col-8">
                            <a asp-controller="Home" asp-action="Overview" asp-route-id="@article.Id" class="black action">
                                <div class="row"><b>Title: </b> &nbsp; @article.Title</div>
                                <div class="row"><b>Content: </b> &nbsp; @article.GetContentSummary()</div>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col col-3">
                    <div class="row"><b>Created At: </b> &nbsp; @article.GetCreatedTime()</div>
                    <br>
                    <div class="row float-right mt-5 mr-4">
                        @if (article.AuthorId.ToString().Equals(Context.Session.GetString("userId")))
                        {
                            <a class="btn btn-sm btn-outline-warning" asp-controller="Article" asp-action="Edit" asp-route-id="@article.Id">
                                <i class="far fa-edit">&nbsp;&nbsp;Edit</i>
                            </a>
                             <a class="btn btn-sm btn-outline-danger ml-2" asp-controller="Article" asp-action="Delete" asp-route-id="@article.Id">
                                <i class="fas fa-ban">&nbsp;&nbsp;Delete</i>
                            </a>
                        }
                    </div>
                </div>
            </div>
        }
    }
</div>

BlogSitesiProjesi/Views/Home/Overview.cshtml
@model OverviewViewModel
@{
    ViewData["Title"] = "Genel bakis";
}

<style>
    pre {
        padding: 0 50px;
        white-space: pre-wrap; /* Since CSS 2.1 */
        white-space: -moz-pre-wrap; /* Mozilla, since 1999 */
        white-space: -pre-wrap; /* Opera 4-6 */
        white-space: -o-pre-wrap; /* Opera 7 */
        word-wrap: break-word; /* Internet Explorer 5.5+ */
        overflow:hidden
    }
</style>

<div class="container-fluid">
    <div class="row text-center">
        <div class="col">
            <div class="card">
                <h2>@Model.Title</h2>
                <h5>@Model.Author, @Model.GetCreatedTime()</h5>
                <div>
                    <img src="~/images/@Model.ArticlePicture" alt="Resim" style="max-height:750px; max-width:750px" />
                </div>
                <br />
                <div>
                    <pre>@Model.Content</pre>
                </div>
            </div>
        </div>
    </div>
</div>

BlogSitesiProjesi/Views/Home/Profile.cshtml
@using Microsoft.AspNetCore.Http
@model List<ArticleViewModel>
@{
    ViewData["Title"] = "Profil";
}

<link href="~/css/article-list.css" rel="stylesheet" />

<div class="container">
    <h2 class="text-center">Son Makaleler</h2>
    @if (TempData["message"] != null)
    {
        <div class="text-success">@TempData["message"]</div>
    }
    @if (TempData["error"] != null)
    {
        <div class="text-danger">@TempData["error"]</div>
    }

    @if (!string.IsNullOrEmpty(Context.Session.GetString("userId")))
    {
        <div style="float:right">
            <a class="btn btn-outline-success" asp-controller="Article" asp-action="Create" asp-route-yonlen="/Home/Profile/@Context.Session.GetString("username")">
                <i class="fas fa-plus">&nbsp;&nbsp;Create</i>
                </a>
        </div>
    }
    <br>
    <br>
    @if (Model is null || Model.Count == 0)
    {
        <h2 class="text-center article-panel brick">Veri yok</h2>
    }
    else
    {
        foreach (ArticleViewModel article in Model)
        {
            <div class="row mb-2 p-1 article-panel">
                <div class="col col-9">
                    <div class="row">
                        <div class="col col-4">
                            <div class="row"><b>Author: </b> &nbsp; @article.AuthorName</div>
                            <div class="row">
                                <img src="~/images/@article.ArticlePicture" alt="Alternate Text" style="object-fit:contain; max-width:200px; max-height:150px;">
                            </div>
                        </div>
                        <div class="col col-8">
                            <a asp-controller="Home" asp-action="Overview" asp-route-id="@article.Id" class="black action">
                                <div class="row"><b>Title: </b> &nbsp; @article.Title</div>
                                <div class="row"><b>Content: </b> &nbsp; @article.GetContentSummary()</div>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col col-3">
                    <div class="row"><b>Created At: </b> &nbsp; @article.GetCreatedTime()</div>
                    <br>
                    <div class="row float-right mt-5 mr-4">
                        @if (article.AuthorId.ToString().Equals(Context.Session.GetString("userId")))
                        {
                            <a class="btn btn-sm btn-outline-warning" asp-controller="Article" asp-action="Edit" asp-route-id="@article.Id">
                                <i class="far fa-edit">&nbsp;&nbsp;Edit</i>
                            </a>
                             <a class="btn btn-sm btn-outline-danger ml-2" asp-controller="Article" asp-action="Delete" asp-route-id="@article.Id">
                                <i class="fas fa-ban">&nbsp;&nbsp;Delete</i>
                            </a>
                        }
                    </div>
                </div>
            </div>
        }
    }
</div>